#   This file holds the configuration for the automated code checks on CodeClimate
version: "2"
checks:
    method-complexity:
        config:
            threshold: 6
plugins:
    pep8:
        enabled: true
exclude_patterns:
    - "**/documentation/"
    - "**/test/"