language: python
python:
  - "3.6"

os:
  - linux

install:
  - pip install -r requirements.txt
  - sudo curl -Lo /usr/local/bin/ssget https://raw.githubusercontent.com/ginkgo-project/ssget/master/ssget

script:
  - pytest

notifications:
  email: false

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true