language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

install:
  - pip install -r requirements.txt

script:
  - pytest

notifications:
  email: false

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true