# This file holds the configuration for the automated builds on travis
sudo: false

branches:
#  Exclude the github pages branch because this branch is only used for uploading the documentation
  except:
    - gh-pages

#  Only linux works because ssget is only available on linux or mac and mac together with python is not supported by travis
os:
  - linux

#  Python is the main coding language, we left out c++ because we do not compile or test it dynamically
language: python

# only version that supports everything we need
python:
  - "3.6"

addons:
  apt:
#    Add package doxygen to generate the documentation afterwards
    packages:
      - doxygen

install:
#  Install and download ssget
  - git clone https://github.com/ginkgo-project/ssget.git
  - cd ssget
  - sudo make install
  - cd ..
#  Install all required python packages
  - pip install -r requirements.txt

# download the test reporter binary that takes care of uploading the test coverage results to code climate
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# run pytest and create a coverage report
script:
  - py.test --cov=modules modules/test/ --cov-report xml:coverage.xml

# this uploads the final results to coverage py
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --coverage-input-type coverage.py

# create the documentation of our classes and funtions
after_success:
  - doxygen Doxyfile

notifications:
  email: false

deploy:
# deploy the documentation to GitHub-Pages
  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GH_REPO_TOKEN
    on:
      branch: master
# run script that creates the GitHub wiki
  - provider: script
    script: bash wiki_deployment.sh
    on:
      branch: master
