language: python
python:
  - "3.6"

os:
  - linux

install:
  - git clone https://github.com/ginkgo-project/ssget.git
  - cd ssget
  - sudo make install
  - cd ..
  - pip install -r requirements.txt

script:
  - pytest

notifications:
  email: false
